[package]
name = "weresocool_rational"
version = "0.1.0"
authors = ["Danny Meyer <danny@xasopheno.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.3.1"
num-rational = "0.3.2"
