name: Continuous Deployment

on:
  push:
    tags:
      ['*']
      # - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Publishing for ${{ matrix.job.os }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - { os: macos-latest,   target: x86_64-apple-darwin,         use-cross: false }
          # - { os: ubuntu-latest , target: x86_64-unknown-linux-gnu,    use-cross: false }
          # - { os: ubuntu-latest,  target: x86_64-unknown-linux-musl,   use-cross: true }
          # - { os: ubuntu-latest,  target: i686-unknown-linux-gnu,      use-cross: true }
          # - { os: ubuntu-latest,  target: arm-unknown-linux-gnueabihf, use-cross: true }
          # - { os: ubuntu-latest,  target: aarch64-unknown-linux-gnu,   use-cross: true }

    steps:
      - uses: extractions/setup-just@v1
      - name: install macos dependancies
        run: brew install portaudio pkg-config lame libvorbis
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract version
        id: extract-version
        run: |
          printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"

      - name: Packaging final binary
        run: ./scripts/package_macos.sh ${{ steps.extract-version.outputs.tag-name }}

      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
           target/release/weresocool-mac-${{ steps.extract-version.outputs.tag-name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set SHA
        id: shasum
        run: |
          echo ::set-output name=sha::"$(shasum -a 256 ./target/release/weresocool-mac-${{ steps.extract-version.outputs.tag-name }}.tar.gz | awk '{printf $1}')"

      - name: Bump Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v2
        if: "!contains(github.ref, '-')"
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
        with:
          base-branch: main
          formula-name: weresocool
          create-pullrequest: true
          homebrew-tap: xasopheno/homebrew-weresocool
          tag-name: ${{ steps.extract-version.outputs.tag-name }}
          download-url: https://github.com/xasopheno/weresocool/releases/latest/download/weresocool-mac-${{ steps.extract-version.outputs.tag-name }}.tar.gz

  # publish-to-cargo:
    # name: Publishing to Cargo
    # runs-on: ubuntu-latest
    # steps:
      # - uses: actions/checkout@master
      # - uses: actions-rs/toolchain@v1
        # with:
          # toolchain: stable
          # profile: minimal
          # override: true
      # - uses: actions-rs/cargo@v1
        # with:
          # command: publish
          # args: --token ${{ secrets.CARGO_API_KEY }} 
            # # --allow-dirty
          
  # bump-homebrew-formula:
    # runs-on: macos-latest
    # steps:
      # - name: Checkout repository
        # uses: actions/checkout@v2
      # - name: Bump Homebrew formulae
        # uses: dawidd6/action-homebrew-bump-formula@v3
        # with:
          # formula: weresocool
          # token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
